import{emptyFrames,gameComplete,activeFrameIndex,nextRollMax,addRoll,undoRoll,rollMark,scoreGame,summarizeSessions,handicapPins,runningLeagueAverage,isSplitLeave,leaveLabel,filterSessionsByMeta,metadataValues,summarizeBreakdown}from'./scoring.mjs';
const APP_VERSION='public-v10',DB='popz-bowling-public',STORE='state',KEY='master',$=id=>document.getElementById(id);let state,toastTimer,pendingLeave=null,leaveSelection=new Set(),editingFrameIndex=null,deferredInstallPrompt=null;
const uuid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`,nowIso=()=>new Date().toISOString();
const todayLocal=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
const defaultState=()=>({version:2,deviceId:uuid(),updatedAt:nowIso(),settingsUpdatedAt:nowIso(),settings:{bowlerName:''},activeSessionId:null,sessions:[],lastBackupAt:null});
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function loadState(){const db=await openDb(),v=await new Promise((ok,no)=>{const r=db.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});db.close();return v||defaultState()}
async function saveState(touch=true){if(touch)state.updatedAt=nowIso();const db=await openDb();await new Promise((ok,no)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(state,KEY);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)});db.close()}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function isInstalled(){return window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function updateInstallButton(){const b=$('installAppBtn');if(b)b.classList.toggle('hidden',isInstalled())}
async function installApp(){if(isInstalled())return toast('Popz Bowling is already installed');if(deferredInstallPrompt){const prompt=deferredInstallPrompt;deferredInstallPrompt=null;prompt.prompt();const choice=await prompt.userChoice;if(choice.outcome==='accepted')toast('Installing Popz Bowling');else toast('Install canceled');updateInstallButton();return}const ua=navigator.userAgent;if(/iphone|ipad|ipod/i.test(ua))return alert('Install Popz Bowling on iPhone/iPad:\n\n1. Open popzbowling.com in Safari.\n2. Tap Share.\n3. Tap Add to Home Screen.\n4. Tap Add.');if(/android/i.test(ua))return alert('Install Popz Bowling on Android:\n\n1. Open popzbowling.com in Chrome.\n2. Refresh the page once if this is your first visit.\n3. Tap Install App here again, or use Chrome menu > Add to Home screen / Install app.');alert('Use your browser’s Install App or Add to Home Screen option to install Popz Bowling.')}
function jumpToFirstFrame(){requestAnimationFrame(()=>requestAnimationFrame(()=>{const first=$('scoreboard')?.querySelector('.frame');(first||$('scoreboard'))?.scrollIntoView({behavior:'smooth',block:'start'})}))}
function closeApp(){try{window.close()}catch{}setTimeout(()=>{$('appShell').classList.add('hidden');document.querySelector('.bottom-nav').classList.add('hidden');$('exitScreen').classList.remove('hidden')},180)}
function reopenApp(){$('exitScreen').classList.add('hidden');$('appShell').classList.remove('hidden');document.querySelector('.bottom-nav').classList.remove('hidden');showView('dashboard')}
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=s=>{if(!s)return'';const[y,m,d]=s.split('-');return`${m}/${d}/${y}`};
function activeSession(){return state.sessions.find(s=>s.id===state.activeSessionId)||null}
function activeGame(){const s=activeSession();if(!s)return null;return[...s.games].reverse().find(g=>!gameComplete(g))||s.games[s.games.length-1]||null}
function touchSession(s){s.updatedAt=nowIso();state.updatedAt=s.updatedAt}
function sessionHandicap(s){return handicapPins(s.enteringAverage,s.handicapPct??90,s.handicapBase??220)}
function gameBall(s,g){return g.ballUsed??s.ballUsed??''} function gameLane(g){return g.lane??''}
const normEntry=v=>String(v??'').trim().replace(/\s+/g,' ').toLocaleLowerCase();
const cleanEntry=v=>String(v??'').trim().replace(/\s+/g,' ');
const canonicalCenter=v=>normEntry(v)==='flightless frt. rucker'?'Flightline Frt. Rucker':cleanEntry(v);
function migrateKnownAliases(){let changed=false;for(const s of state.sessions||[]){if(normEntry(s.center)==='flightless frt. rucker'){s.center='Flightline Frt. Rucker';s.updatedAt=nowIso();changed=true}}if(normEntry(state.settings?.statsCenter)==='flightless frt. rucker'){state.settings.statsCenter='Flightline Frt. Rucker';state.settingsUpdatedAt=nowIso();changed=true}if(changed)state.updatedAt=nowIso();return changed}
function distinctEntries(values=[]){const m=new Map();for(const raw of values){const v=cleanEntry(raw),k=normEntry(v);if(k)m.set(k,v)}return[...m.values()].sort((a,b)=>a.localeCompare(b))}
function rememberedEntries(kind){const out=[];for(const s of state.sessions||[]){if(kind==='league')out.push(s.league);else if(kind==='center')out.push(canonicalCenter(s.center));else if(kind==='oil')out.push(s.oilPattern);else for(const g of s.games||[])out.push(kind==='ball'?gameBall(s,g):gameLane(g))}return distinctEntries(out)}
function renderRememberedEntries(){[['leagueOptions','league'],['centerOptions','center'],['oilOptions','oil'],['ballOptions','ball'],['laneOptions','lane']].forEach(([id,kind])=>{$(id).replaceChildren(...rememberedEntries(kind).map(v=>new Option(v,v)))})}
function frameStrip(g){const sc=scoreGame(g);return`<div class="history-frames">${g.frames.map((f,i)=>{const slots=i===9?3:2,marks=Array.from({length:slots},(_,j)=>`<span>${esc(rollMark(f,i,j))||'·'}</span>`).join('');return`<div class="history-frame"><b>${i+1}</b><div>${marks}</div><strong>${sc.cumulative[i]??''}</strong></div>`}).join('')}</div>`}
function leaveHistory(g){const rows=g.frames.map((f,i)=>{if(!f.leave?.length)return'';const made=(f.rolls?.length>1&&f.rolls[0]+f.rolls[1]===10),split=f.split||isSplitLeave(f.leave);return`<span>F${i+1}: ${esc(leaveLabel(f.leave))}${split?' SPLIT':''} ${made?'✓':'✗'}</span>`}).filter(Boolean);return rows.length?`<div class="leave-history">${rows.join('')}</div>`:''}
function sessionRow(s){const complete=(s.games||[]).filter(gameComplete),scores=complete.map(g=>scoreGame(g).final),total=scores.reduce((a,b)=>a+b,0),hdcp=sessionHandicap(s),details=[fmtDate(s.date),s.league,s.center,s.oilPattern&&`Oil: ${s.oilPattern}`,Number.isFinite(hdcp)&&`HDCP: ${s.handicapPct??90}% of ${s.handicapBase??220} = ${hdcp}`,`${s.games?.length||0}/${s.gameCount||3} games`].filter(Boolean).map(esc).join(' • '),games=(s.games||[]).map((g,i)=>{const scratch=gameComplete(g)?scoreGame(g).final:null,ball=gameBall(s,g),lane=gameLane(g),meta=[lane&&`Lane ${lane}`,ball&&`Ball: ${ball}`].filter(Boolean).map(esc).join(' • '),scoreText=scratch==null?'Incomplete':Number.isFinite(hdcp)?`${scratch} + ${hdcp} = ${scratch+hdcp}`:String(scratch);return`<div class="history-game"><div class="history-game-title"><div><strong>Game ${i+1}</strong><small>${meta||'No game details'}</small></div><span>${scoreText}</span></div>${frameStrip(g)}${leaveHistory(g)}</div>`}).join('');return`<details class="list-item history-series"><summary><div><strong>${esc(s.name||s.league||'Bowling Series')}</strong><small>${details||'No details'}</small></div><div class="score-chips">${scores.map(x=>`<span class="chip">${x}</span>`).join('')}${scores.length>1?`<span class="chip">Σ ${total}</span>`:''}</div></summary><div class="series-details">${games||'<div class="empty-state">No games recorded.</div>'}</div></details>`}
function pct(v){return v==null?'—':`${v.toFixed(1)}%`}
function leagueName(s){return String(s?.league||'').trim()}
function statsFilterValue(){return state.settings?.statsFilter||'all'}
function isPracticeSession(s){const n=leagueName(s).toLowerCase();return !n||n==='practice'}
function filteredSessions(){const f=statsFilterValue();if(f==='all')return state.sessions;if(f==='leagues')return state.sessions.filter(s=>!isPracticeSession(s));if(f==='practice')return state.sessions.filter(isPracticeSession);if(f.startsWith('league:')){let name='';try{name=decodeURIComponent(f.slice(7))}catch{}return state.sessions.filter(s=>normEntry(leagueName(s))===normEntry(name))}return state.sessions}
function fillStatsSelect(id,key,values,allLabel){const sel=$(id),current=state.settings?.[key]||'',match=values.find(v=>normEntry(v)===normEntry(current))||'';sel.replaceChildren(new Option(allLabel,''),...values.map(v=>new Option(v,v)));sel.value=match;if(current&&!match)state.settings[key]='';}
function metaFilters(){return{center:state.settings?.statsCenter||'',lane:state.settings?.statsLane||'',ball:state.settings?.statsBall||'',oil:state.settings?.statsOil||''}}
function renderStatsFilter(){const sel=$('statsFilter'),names=distinctEntries(state.sessions.filter(s=>!isPracticeSession(s)).map(leagueName).filter(Boolean)),current=statsFilterValue();sel.innerHTML='<option value="all">All Bowling</option><option value="leagues">All Leagues</option><option value="practice">Practice</option>'+names.map(n=>`<option value="league:${encodeURIComponent(n)}">${esc(n)}</option>`).join('');let desired=current;if(current.startsWith('league:')){let name='';try{name=decodeURIComponent(current.slice(7))}catch{}const match=names.find(n=>normEntry(n)===normEntry(name));desired=match?`league:${encodeURIComponent(match)}`:'all'}sel.value=[...sel.options].some(o=>o.value===desired)?desired:'all';if(sel.value!==current)state.settings.statsFilter=sel.value;const base=filteredSessions();fillStatsSelect('centerFilter','statsCenter',metadataValues(base,'center'),'All Centers');const laneBase=filterSessionsByMeta(base,{center:state.settings?.statsCenter||''});fillStatsSelect('laneFilter','statsLane',metadataValues(laneBase,'lane'),'All Lanes');fillStatsSelect('ballFilter','statsBall',metadataValues(base,'ball'),'All Balls');fillStatsSelect('oilFilter','statsOil',metadataValues(base,'oil'),'All Oil Patterns');const parts=[sel.selectedOptions[0]?.textContent||'All Bowling'];[['centerFilter','All Centers'],['laneFilter','All Lanes'],['ballFilter','All Balls'],['oilFilter','All Oil Patterns']].forEach(([id,all])=>{const x=$(id);if(x.value)parts.push(x.selectedOptions[0]?.textContent||all)});$('statsFilterSummary').textContent=parts.join(' • ')}
function filteredAnalyticsSessions(){return filterSessionsByMeta(filteredSessions(),metaFilters())}
function leagueSessionsByName(name){return state.sessions.filter(s=>!isPracticeSession(s)&&normEntry(leagueName(s))===normEntry(name))}
function leagueRunningByName(name){return name?runningLeagueAverage(leagueSessionsByName(name)):null}
function namedSessionsByName(name,excludeId=''){const key=normEntry(name);if(!key)return[];return state.sessions.filter(s=>s.id!==excludeId&&normEntry(leagueName(s))===key)}
function suggestedAverageByName(name,excludeId=''){const sessions=namedSessionsByName(name,excludeId);if(!sessions.length)return null;if(normEntry(name)==='practice'){const st=summarizeSessions(sessions);return st.average}const run=runningLeagueAverage(sessions);if(run)return run.currentAverage;const st=summarizeSessions(sessions);return st.average}
function selectedLeagueName(){const f=statsFilterValue();if(!f.startsWith('league:'))return'';try{return decodeURIComponent(f.slice(7))}catch{return''}}
function renderLeagueAverage(){const panel=$('leagueAveragePanel'),name=selectedLeagueName(),run=leagueRunningByName(name);panel.classList.toggle('hidden',!name);if(!name)return;$('leagueBookAverage').textContent=run?run.seedAverage.toFixed(1):'—';$('leagueLatestAverage').textContent=run?.latestAverage==null?'—':run.latestAverage.toFixed(1);$('leagueCurrentAverage').textContent=run?run.currentAverage.toFixed(1):'—';$('leagueGamesAdded').textContent=run?.games??0}
function suggestEnteringAverage(){const name=cleanEntry($('seriesLeague').value),avg=suggestedAverageByName(name);if(avg!=null)$('seriesEnteringAverage').value=avg.toFixed(1)}
function renderBreakdown(id,rows){$(id).innerHTML=rows.length?rows.map(r=>`<div class="breakdown-row"><strong>${esc(r.label)}</strong><span><small>Games</small><b>${r.games}</b></span><span><small>Average</small><b>${r.average==null?'—':r.average.toFixed(1)}</b></span><span><small>High Game</small><b>${r.highGame??'—'}</b></span><span><small>Strike %</small><b>${pct(r.strikePct)}</b></span><span><small>Spare %</small><b>${pct(r.sparePct)}</b></span></div>`).join(''):'<div class="empty-state compact-empty">No recorded data yet.</div>'}
function renderDashboard(){renderStatsFilter();renderLeagueAverage();const base=filteredSessions(),laneBase=filterSessionsByMeta(base,{center:state.settings?.statsCenter||''}),sessions=filteredAnalyticsSessions(),st=summarizeSessions(sessions);$('welcomeName').textContent=state.settings.bowlerName?`${state.settings.bowlerName}'s Bowling Dashboard`:'Bowling Dashboard';$('statAverage').textContent=st.average==null?'—':st.average.toFixed(1);$('statHighGame').textContent=st.highGame??'—';$('statHighSeries').textContent=st.highSeries??'—';$('statGames').textContent=st.games;$('statStrike').textContent=pct(st.strikePct);$('statSpare').textContent=pct(st.sparePct);$('statSplit').textContent=pct(st.splitPct);$('statSinglePin').textContent=pct(st.singlePinPct);$('statTenPin').textContent=pct(st.tenPinPct);renderBreakdown('centerBreakdown',summarizeBreakdown(base,'center'));renderBreakdown('laneBreakdown',summarizeBreakdown(laneBase,'lane'));renderBreakdown('ballBreakdown',summarizeBreakdown(base,'ball'));renderBreakdown('oilBreakdown',summarizeBreakdown(base,'oil'));$('leaveStats').innerHTML=st.leaveDetails?.length?st.leaveDetails.map(x=>`<div class="leave-stat-card"><div class="leave-stat-title"><strong>${x.pins?.length===1?`${esc(x.label)}-pin`:esc(x.label)}</strong>${x.split?'<span class="split-badge">SPLIT</span>':''}</div><div class="leave-stat-numbers"><span><b>${x.attempts}</b> attempts</span><span><b>${x.made}</b> made</span><span><b>${x.pct==null?'—':x.pct.toFixed(1)+'%'}</b> conversion</span></div></div>`).join(''):'<div class="empty-state">No first-ball pin leaves recorded in this stats view yet.</div>';$('lastSyncText').textContent=state.lastBackupAt?`Last backup exported: ${new Date(state.lastBackupAt).toLocaleString()}`:'Your bowling data is stored only on this device. Export a backup occasionally.';const r=[...sessions].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,5);$('recentSeries').innerHTML=r.length?r.map(sessionRow).join(''):'<div class="empty-state">No sessions in this stats view.</div>'}
function renderSeriesSummary(s){const complete=(s.games||[]).filter(gameComplete),scores=complete.map(g=>scoreGame(g).final),total=scores.reduce((a,b)=>a+b,0),st=summarizeSessions([s]),hdcp=sessionHandicap(s),hdcpTotal=Number.isFinite(hdcp)&&complete.length?total+(hdcp*complete.length):null;$('seriesSummaryTitle').textContent=s.name||s.league||'Series Complete';$('seriesSummaryMeta').textContent=[fmtDate(s.date),s.league,s.center,s.oilPattern&&`Oil: ${s.oilPattern}`,`${complete.length} completed game${complete.length===1?'':'s'}`].filter(Boolean).join(' • ');$('summarySeriesTotal').textContent=complete.length?total:'—';$('summaryAverage').textContent=st.average==null?'—':st.average.toFixed(1);$('summaryHighGame').textContent=st.highGame??'—';$('summaryGames').textContent=st.games;$('summaryHdcpSeries').textContent=hdcpTotal??'—';$('summaryStrike').textContent=pct(st.strikePct);$('summarySpare').textContent=pct(st.sparePct);$('summarySplit').textContent=pct(st.splitPct);$('summarySinglePin').textContent=pct(st.singlePinPct);$('summaryTenPin').textContent=pct(st.tenPinPct);$('seriesSummaryGames').innerHTML=complete.length?complete.map(g=>{const i=s.games.indexOf(g),score=scoreGame(g).final,ball=gameBall(s,g),lane=gameLane(g),meta=[lane&&`Lane ${lane}`,ball&&`Ball: ${ball}`].filter(Boolean).map(esc).join(' • '),hdcpScore=Number.isFinite(hdcp)?score+hdcp:null;return`<div class="list-item summary-game-row"><div><strong>Game ${i+1}</strong><small>${meta||'No game details'}</small></div><div class="score-chips"><span class="chip">Scratch ${score}</span>${hdcpScore!=null?`<span class="chip">HDCP ${hdcpScore}</span>`:''}</div></div>`}).join(''):'<div class="empty-state">No completed games in this series.</div>';$('seriesSummaryLeaves').innerHTML=st.leaveDetails?.length?st.leaveDetails.map(x=>`<div class="leave-stat-card"><div class="leave-stat-title"><strong>${x.pins?.length===1?`${esc(x.label)}-pin`:esc(x.label)}</strong>${x.split?'<span class="split-badge">SPLIT</span>':''}</div><div class="leave-stat-numbers"><span><b>${x.attempts}</b> attempts</span><span><b>${x.made}</b> made</span><span><b>${x.pct==null?'—':x.pct.toFixed(1)+'%'}</b> conversion</span></div></div>`).join(''):'<div class="empty-state">No first-ball pin leaves recorded in this series.</div>'}
function renderHistory(){const l=[...state.sessions].sort((a,b)=>(b.date||'').localeCompare(a.date||''));$('historyList').innerHTML=l.length?l.map(sessionRow).join(''):'<div class="empty-state">No history yet.</div>'}
function renderSettings(){$('bowlerName').value=state.settings.bowlerName||'';$('appVersion').textContent=APP_VERSION}
function renderScoring(){const s=activeSession();$('seriesSetup').classList.toggle('hidden',!!s);$('scoringArea').classList.toggle('hidden',!s);if(!s){editingFrameIndex=null;return}$('activeSeriesTitle').textContent=s.name||s.league||'Current Series';const hdcp=sessionHandicap(s);$('activeSeriesMeta').textContent=[fmtDate(s.date),s.league,s.center,s.oilPattern&&`Oil: ${s.oilPattern}`,`${s.gameCount||3} games`].filter(Boolean).join(' • ');const g=activeGame(),sc=scoreGame(g),a=activeFrameIndex(g),completeGames=s.games.filter(gameComplete),seriesScratch=completeGames.reduce((n,x)=>n+(scoreGame(x).final||0),0);$('currentGameNo').textContent=`${s.games.indexOf(g)+1} / ${s.gameCount||3}`;$('currentScore').textContent=sc.final??sc.total;$('currentHandicap').textContent=Number.isFinite(hdcp)?hdcp:'—';$('currentHdcpScore').textContent=sc.final!=null&&Number.isFinite(hdcp)?sc.final+hdcp:'—';$('currentSeriesScore').textContent=seriesScratch;$('currentSeriesHdcp').textContent=Number.isFinite(hdcp)&&completeGames.length?seriesScratch+(hdcp*completeGames.length):'—';$('handicapFormula').textContent=Number.isFinite(hdcp)?`${s.handicapPct??90}% of ${s.handicapBase??220} • Avg ${s.enteringAverage} = ${hdcp}/game`:'Enter an average to calculate';$('currentBallUsed').value=gameBall(s,g);$('currentLane').value=gameLane(g);$('currentEnteringAverage').value=s.enteringAverage==null?'':s.enteringAverage;$('scoreboard').innerHTML=g.frames.map((f,i)=>{const slots=i===9?3:2,marks=Array.from({length:slots},(_,j)=>`<div class="roll">${rollMark(f,i,j)}</div>`).join(''),leave=f.leave?.length?`<div class="frame-leave ${f.split?'split':''}">${leaveLabel(f.leave)}</div>`:'',editable=f.rolls?.length&&(gameComplete(g)||i<a);return`<div class="frame ${!gameComplete(g)&&i===a?'active-frame':''} ${editable?'editable-frame':''}" ${editable?`data-edit-frame="${i}"`:''}><div class="frame-no">${i+1}${editable?' ✎':''}</div><div class="rolls">${marks}</div><div class="frame-score">${sc.cumulative[i]??''}</div>${leave}</div>`}).join('');if(editingFrameIndex!=null)renderFrameEditor(g);else $('frameEditor').classList.add('hidden');renderPinPad(g)}
function renderPinDeck(){const deck=$('pinDeck'),rows=[[7,8,9,10],[4,5,6],[2,3],[1]];deck.innerHTML=rows.map(r=>`<div class="pin-row">${r.map(n=>`<button class="pin ${leaveSelection.has(n)?'standing':''}" data-pin="${n}">${n}</button>`).join('')}</div>`).join('');$('leaveCount').textContent=`${leaveSelection.size} of ${pendingLeave.expected} selected`;const split=isSplitLeave([...leaveSelection]);$('leavePrompt').textContent=split?'Mark pins left standing — SPLIT detected':'Mark pins left standing'}
function renderPinPad(g){const pad=$('pinPad'),tracker=$('leaveTracker');if(pendingLeave&&pendingLeave.gameId===g.id){tracker.classList.remove('hidden');pad.classList.add('hidden');$('rollPrompt').textContent=`Frame ${pendingLeave.frameIndex+1}: identify the ${pendingLeave.expected} pins left standing`;renderPinDeck();return}tracker.classList.add('hidden');pad.classList.remove('hidden');if(gameComplete(g)){const s=activeSession(),target=s?.gameCount||3,done=(s?.games?.length||0)>=target;$('rollPrompt').textContent=done?`Series target complete — Game ${scoreGame(g).final}`:`Game complete — ${scoreGame(g).final}`;pad.innerHTML=done?'<button class="special" data-finish-series="1">Finish Series</button>':'<button class="special" data-new-game="1">Start Next Game</button>';return}const i=activeFrameIndex(g),r=g.frames[i].rolls,max=nextRollMax(g);$('rollPrompt').textContent=`Frame ${i+1} • Ball ${r.length+1} • ${max} pins standing`;const b=[];for(let n=0;n<=max;n++){let label=n===0?'–':String(n);if(n===10)label='X';if(r.length&&n===max&&max<10)label='/';b.push(`<button class="${label==='X'||label==='/'?'special':''}" data-pins="${n}">${label}</button>`)}pad.innerHTML=b.join('')}

function frameEditRolls(i,a,b,c){if(!Number.isInteger(a)||a<0||a>10)throw Error('Ball 1 must be 0–10');if(i<9){if(a===10)return[10];if(!Number.isInteger(b)||b<0||b>10-a)throw Error(`Ball 2 must be 0–${10-a}`);return[a,b]}if(a===10){if(!Number.isInteger(b)||b<0||b>10)throw Error('Ball 2 must be 0–10');const max3=b===10?10:10-b;if(!Number.isInteger(c)||c<0||c>max3)throw Error(`Ball 3 must be 0–${max3}`);return[a,b,c]}if(!Number.isInteger(b)||b<0||b>10-a)throw Error(`Ball 2 must be 0–${10-a}`);if(a+b===10){if(!Number.isInteger(c)||c<0||c>10)throw Error('Ball 3 must be 0–10');return[a,b,c]}return[a,b]}
function openFrameEditor(i){const g=activeGame();if(!g||!g.frames[i]?.rolls?.length)return;editingFrameIndex=i;renderFrameEditor(g);$('frameEditor').scrollIntoView({behavior:'smooth',block:'nearest'})}
function renderFrameEditor(g){const f=g.frames[editingFrameIndex];if(!f){editingFrameIndex=null;$('frameEditor').classList.add('hidden');return}$('frameEditor').classList.remove('hidden');$('frameEditorTitle').textContent=`Edit Frame ${editingFrameIndex+1}`;$('editBall1').value=f.rolls[0]??'';$('editBall2').value=f.rolls[1]??'';$('editBall3').value=f.rolls[2]??'';$('editBall3Wrap').classList.toggle('hidden',editingFrameIndex!==9)}
async function saveFrameEdit(){const s=activeSession(),g=activeGame();if(!s||!g||editingFrameIndex==null)return;try{const f=g.frames[editingFrameIndex],oldFirst=f.rolls?.[0],num=id=>$(id).value===''?NaN:Number($(id).value),rolls=frameEditRolls(editingFrameIndex,num('editBall1'),num('editBall2'),num('editBall3'));f.rolls=rolls;if(oldFirst!==rolls[0]){delete f.leave;delete f.split}g.updatedAt=nowIso();touchSession(s);editingFrameIndex=null;await saveState(false);renderAll();toast(`Frame ${g.frames.indexOf(f)+1} corrected`)}catch(e){toast(e.message)}}
function cancelFrameEdit(){editingFrameIndex=null;$('frameEditor').classList.add('hidden')}

async function startSeries(){const gameCount=Math.max(1,Math.min(12,Number($('seriesGameCount').value)||3)),league=cleanEntry($('seriesLeague').value),typedAverage=$('seriesEnteringAverage').value===''?null:Number($('seriesEnteringAverage').value),enteringAverage=typedAverage??suggestedAverageByName(league),handicapPct=Number($('seriesHandicapPct').value)||0,handicapBase=Number($('seriesHandicapBase').value)||0;const s={id:uuid(),date:$('seriesDate').value||todayLocal(),center:canonicalCenter($('seriesCenter').value),league,gameCount,oilPattern:cleanEntry($('seriesOilPattern').value),enteringAverage,handicapPct,handicapBase,name:cleanEntry($('seriesName').value),createdAt:nowIso(),updatedAt:nowIso(),games:[{id:uuid(),createdAt:nowIso(),ballUsed:'',lane:'',frames:emptyFrames()}]};state.sessions.push(s);state.activeSessionId=s.id;pendingLeave=null;leaveSelection.clear();await saveState();renderAll();jumpToFirstFrame();toast(`${gameCount}-game series started`)}
async function recordRoll(pins){const s=activeSession(),g=activeGame();if(!s||!g||pendingLeave)return;try{const fi=activeFrameIndex(g),before=g.frames[fi].rolls.length;addRoll(g,pins);g.updatedAt=nowIso();touchSession(s);if(before===0&&pins<10){pendingLeave={gameId:g.id,frameIndex:fi,expected:10-pins};leaveSelection=new Set()}await saveState(false);renderAll();if(gameComplete(g))toast(`Game ${scoreGame(g).final}`)}catch(e){toast(e.message)}}
async function saveLeave(){const s=activeSession(),g=activeGame();if(!s||!g||!pendingLeave)return;if(leaveSelection.size!==pendingLeave.expected)return toast(`Select exactly ${pendingLeave.expected} standing pins`);const f=g.frames[pendingLeave.frameIndex],pins=[...leaveSelection].sort((a,b)=>a-b);f.leave=pins;f.split=isSplitLeave(pins);g.updatedAt=nowIso();touchSession(s);pendingLeave=null;leaveSelection.clear();await saveState(false);renderAll();toast(f.split?`Split saved: ${leaveLabel(pins)}`:`Leave saved: ${leaveLabel(pins)}`)}
async function undo(){const s=activeSession(),g=activeGame();if(pendingLeave){pendingLeave=null;leaveSelection.clear()}if(g&&undoRoll(g)){touchSession(s);await saveState(false);renderAll();toast('Last roll removed')}}
async function newGame(){const s=activeSession();if(!s)return;pendingLeave=null;leaveSelection.clear();const target=s.gameCount||3;if(s.games.length>=target)return toast(`Series is set for ${target} games`);const g=activeGame();if(g&&!gameComplete(g)&&g.frames.some(f=>f.rolls.length)&&!confirm('Current game is not finished. Start another game anyway?'))return;if(g&&!gameComplete(g)&&!g.frames.some(f=>f.rolls.length))return toast('New game already ready');s.games.push({id:uuid(),createdAt:nowIso(),ballUsed:gameBall(s,g),lane:gameLane(g),frames:emptyFrames()});touchSession(s);await saveState(false);renderAll();jumpToFirstFrame();toast(`Game ${s.games.length} ready`)}
async function saveGameDetail(key,value){const s=activeSession(),g=activeGame();if(!s||!g)return;g[key]=value;g.updatedAt=nowIso();touchSession(s);const firstBall=!g.frames.some(f=>f.rolls?.length);await saveState(false);renderAll();if(firstBall)jumpToFirstFrame();toast(key==='ballUsed'?'Ball saved':'Lane saved')}
async function saveEnteringAverage(){const s=activeSession();if(!s)return;const raw=$('currentEnteringAverage').value,avg=raw===''?suggestedAverageByName(s.league,s.id):Number(raw);if(avg==null||!Number.isFinite(avg)||avg<0||avg>300)return toast('Enter an average from 0 to 300');s.enteringAverage=avg;touchSession(s);await saveState(false);renderAll();toast(`Average ${avg.toFixed(1)} saved • handicap updated`)}
async function deleteCurrentGame(){const s=activeSession(),g=activeGame();if(!s||!g)return;if((s.games||[]).length<=1)return toast('Cannot delete the only game in a series');const gameNo=s.games.indexOf(g)+1,hasRolls=g.frames.some(f=>f.rolls?.length);if(!confirm(`Delete Game ${gameNo}${hasRolls?' and all recorded frames':''}?`))return;pendingLeave=null;leaveSelection.clear();s.games=s.games.filter(x=>x.id!==g.id);if((s.gameCount||3)>s.games.length)s.gameCount=s.games.length;touchSession(s);await saveState(false);renderAll();toast(`Game ${gameNo} deleted • series now ${s.gameCount} games`)}
async function finishSeries(){const s=activeSession();if(!s)return;pendingLeave=null;leaveSelection.clear();const g=activeGame();if(g&&!gameComplete(g)&&g.frames.some(f=>f.rolls.length)&&!confirm('The current game is incomplete. Finish the series anyway?'))return;s.finishedAt=nowIso();touchSession(s);state.activeSessionId=null;await saveState(false);renderAll();renderSeriesSummary(s);showView('seriesSummary');toast('Series saved locally')}
async function exportBackup(){state.lastBackupAt=nowIso();await saveState(false);const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`popz-bowling-backup-${todayLocal()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);renderDashboard();toast('Backup exported — save it somewhere safe')}
function shareFeedback(){const note=$('feedbackText').value.trim();if(!note)return toast('Type your feedback first');const subject='Popz Bowling Stats',body=`${note}\n\nApp: ${APP_VERSION}\nDevice: ${navigator.userAgent}`,mailto=`mailto:feedback@popzbowling.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;window.location.href=mailto;toast('Opening your email app') }
async function importBackup(file){try{const d=JSON.parse(await file.text());if(!d||!Array.isArray(d.sessions))throw Error('Invalid bowling backup');state={...defaultState(),...d,deviceId:state.deviceId,updatedAt:nowIso()};await saveState(false);renderAll();toast('Backup imported')}catch(e){toast(e.message||'Import failed')}}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`${name}View`).classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='history')renderHistory();if(name==='settings')renderSettings();if(name==='bowl')renderScoring()}
function renderAll(){renderRememberedEntries();renderDashboard();renderHistory();renderSettings();renderScoring()}
function bind(){$('installAppBtn').addEventListener('click',installApp);$('closeAppBtn').addEventListener('click',closeApp);$('reopenAppBtn').addEventListener('click',reopenApp);$('seriesSummaryStatsBtn').addEventListener('click',()=>showView('dashboard'));$('seriesSummaryHistoryBtn').addEventListener('click',()=>showView('history'));document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.nav)));$('statsFilter').addEventListener('change',async e=>{state.settings.statsFilter=e.target.value;state.settingsUpdatedAt=nowIso();await saveState();renderDashboard()});[['centerFilter','statsCenter'],['laneFilter','statsLane'],['ballFilter','statsBall'],['oilFilter','statsOil']].forEach(([id,key])=>$(id).addEventListener('change',async e=>{state.settings[key]=e.target.value;state.settingsUpdatedAt=nowIso();await saveState();renderDashboard()}));$('scoreboard').addEventListener('click',e=>{const f=e.target.closest('[data-edit-frame]');if(f)openFrameEditor(Number(f.dataset.editFrame))});$('saveFrameEditBtn').addEventListener('click',saveFrameEdit);$('cancelFrameEditBtn').addEventListener('click',cancelFrameEdit);$('startSeriesBtn').addEventListener('click',startSeries);$('seriesLeague').addEventListener('change',suggestEnteringAverage);$('seriesLeague').addEventListener('blur',suggestEnteringAverage);$('pinPad').addEventListener('click',e=>{const p=e.target.dataset.pins;if(p!=null)recordRoll(Number(p));if(e.target.dataset.newGame)newGame();if(e.target.dataset.finishSeries)finishSeries()});$('pinDeck').addEventListener('click',e=>{const p=e.target.dataset.pin;if(p==null)return;const n=Number(p);leaveSelection.has(n)?leaveSelection.delete(n):leaveSelection.add(n);renderPinDeck()});$('clearLeaveBtn').addEventListener('click',()=>{leaveSelection.clear();renderPinDeck()});$('saveLeaveBtn').addEventListener('click',saveLeave);$('currentBallUsed').addEventListener('change',()=>saveGameDetail('ballUsed',cleanEntry($('currentBallUsed').value)));$('currentLane').addEventListener('change',()=>saveGameDetail('lane',cleanEntry($('currentLane').value)));$('currentEnteringAverage').addEventListener('change',saveEnteringAverage);$('undoRollBtn').addEventListener('click',undo);$('newGameBtn').addEventListener('click',newGame);$('deleteGameBtn').addEventListener('click',deleteCurrentGame);$('finishSeriesBtn').addEventListener('click',finishSeries);$('backupNowHero').addEventListener('click',exportBackup);$('backupNowSettings').addEventListener('click',exportBackup);$('shareFeedbackBtn').addEventListener('click',shareFeedback);$('printGuideBtn').addEventListener('click',()=>window.print());$('exportBtn').addEventListener('click',exportBackup)}
function bindSettings(){$('bowlerName').addEventListener('change',async e=>{state.settings.bowlerName=e.target.value.trim();state.settingsUpdatedAt=nowIso();await saveState();renderAll()});$('importFile').addEventListener('change',e=>e.target.files[0]&&importBackup(e.target.files[0]));$('resetBtn').addEventListener('click',async()=>{if(confirm('Delete all bowling data stored on this device? Make sure you exported a backup first.')){state=defaultState();await saveState(false);renderAll();toast('Local data reset')}})}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;updateInstallButton()});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;updateInstallButton();toast('Popz Bowling installed')});
async function init(){state=await loadState();if(migrateKnownAliases())await saveState(false);$('seriesDate').value=todayLocal();$('seriesGameCount').value=3;$('seriesHandicapPct').value=90;$('seriesHandicapBase').value=220;bind();bindSettings();renderAll();updateInstallButton();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
init();
