export const emptyFrames=()=>Array.from({length:10},()=>({rolls:[]}));
export function frameComplete(frame,index){const r=frame?.rolls||[];if(index<9)return r[0]===10||r.length>=2;if(r.length<2)return false;return(r[0]===10||r[0]+r[1]===10)?r.length>=3:true;}
export const gameComplete=g=>g.frames.every((f,i)=>frameComplete(f,i));
export function activeFrameIndex(g){const i=g.frames.findIndex((f,n)=>!frameComplete(f,n));return i===-1?9:i;}
export function nextRollMax(g){const i=activeFrameIndex(g),r=g.frames[i].rolls;if(i<9){if(!r.length)return 10;if(r[0]===10)return 0;return 10-r[0];}if(!r.length)return 10;if(r.length===1)return r[0]===10?10:10-r[0];if(r.length>=3)return 0;if(r[0]===10)return r[1]===10?10:10-r[1];if(r[0]+r[1]===10)return 10;return 0;}
export function addRoll(g,pins){if(gameComplete(g))throw Error('Game is complete');const max=nextRollMax(g);if(!Number.isInteger(pins)||pins<0||pins>max)throw Error(`Pins must be 0-${max}`);g.frames[activeFrameIndex(g)].rolls.push(pins);return g;}
export function undoRoll(g){for(let i=9;i>=0;i--){if(g.frames[i].rolls.length){g.frames[i].rolls.pop();if(g.frames[i].rolls.length===0){delete g.frames[i].leave;delete g.frames[i].split;}return true;}}return false;}
export function rollMark(frame,index,j){const r=frame.rolls,n=r[j];if(n==null)return'';if(index<9){if(j===0&&n===10)return'X';if(j===1&&r[0]+n===10)return'/';return n===0?'-':String(n);}if(n===0)return'-';if(j===0&&n===10)return'X';if(j===1){if(r[0]!==10&&r[0]+n===10)return'/';if(n===10)return'X';}if(j===2){if(n===10)return'X';if(r[0]===10&&r[1]!==10&&r[1]+n===10)return'/';}return String(n);}
function flatData(g){const flat=[],starts=[];g.frames.forEach(f=>{starts.push(flat.length);flat.push(...f.rolls)});return{flat,starts};}
export function scoreGame(g){const{flat,starts}=flatData(g),cum=Array(10).fill(null);let total=0;for(let i=0;i<10;i++){const r=g.frames[i].rolls,start=starts[i];let fs=null;if(i<9){if(r[0]===10){if(flat[start+1]!=null&&flat[start+2]!=null)fs=10+flat[start+1]+flat[start+2];}else if(r.length>=2){if(r[0]+r[1]===10){if(flat[start+2]!=null)fs=10+flat[start+2];}else fs=r[0]+r[1];}}else if(frameComplete(g.frames[9],9))fs=r.reduce((a,b)=>a+b,0);if(fs==null)break;total+=fs;cum[i]=total;}return{total,cumulative:cum,final:gameComplete(g)?total:null};}
export function handicapPins(avg,pct=90,base=220){if(avg===null||avg===undefined||avg===''||!Number.isFinite(Number(avg)))return null;return Math.max(0,Math.floor((Number(base)-Number(avg))*(Number(pct)/100)));}
export function runningLeagueAverage(sessions=[]){const ordered=[...sessions].filter(s=>String(s?.league||'').trim()).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||(a.createdAt||'').localeCompare(b.createdAt||'')),seed=ordered.find(s=>Number.isFinite(Number(s.enteringAverage)));if(!seed)return null;const seedAverage=Number(seed.enteringAverage),seedGames=Math.max(1,Number(seed.gameCount)||3);let pins=0,games=0;for(const s of ordered)for(const g of(s.games||[]))if(gameComplete(g)){pins+=scoreGame(g).final||0;games++;}const currentAverage=(seedAverage*seedGames+pins)/(seedGames+games),latest=[...ordered].reverse().find(s=>(s.games||[]).some(gameComplete)),latestScores=latest?(latest.games||[]).filter(gameComplete).map(g=>scoreGame(g).final):[],latestAverage=latestScores.length?latestScores.reduce((a,b)=>a+b,0)/latestScores.length:null;return{seedAverage,seedGames,pins,games,currentAverage,latestAverage,totalGames:seedGames+games};}
const xy={1:[2,0],2:[1.5,1],3:[2.5,1],4:[1,2],5:[2,2],6:[3,2],7:[.5,3],8:[1.5,3],9:[2.5,3],10:[3.5,3]};
export function isSplitLeave(pins=[]){const a=[...new Set(pins.map(Number))].filter(n=>n>=1&&n<=10);if(a.length<2||a.includes(1))return false;const near=(x,y)=>{const A=xy[x],B=xy[y],dx=A[0]-B[0],dy=A[1]-B[1];return Math.hypot(dx,dy)<=1.15};const seen=new Set([a[0]]),q=[a[0]];while(q.length){const x=q.shift();for(const y of a)if(!seen.has(y)&&near(x,y)){seen.add(y);q.push(y)}}return seen.size<a.length;}
export function leaveLabel(pins=[]){return pins?.length?[...pins].sort((a,b)=>a-b).join('-'):'—';}
const metaText=v=>String(v??'').trim().replace(/\s+/g,' ');
const metaKey=v=>metaText(v).toLocaleLowerCase();
function metaValue(s,g,kind){if(kind==='center')return metaText(s.center);if(kind==='oil')return metaText(s.oilPattern);if(kind==='lane')return metaText(g?.lane);if(kind==='ball')return metaText(g?.ballUsed??s.ballUsed);return'';}
export function filterSessionsByMeta(sessions=[],filters={}){return sessions.filter(s=>!filters.center||metaKey(metaValue(s,null,'center'))===metaKey(filters.center)).filter(s=>!filters.oil||metaKey(metaValue(s,null,'oil'))===metaKey(filters.oil)).map(s=>({...s,games:(s.games||[]).filter(g=>(!filters.lane||metaKey(metaValue(s,g,'lane'))===metaKey(filters.lane))&&(!filters.ball||metaKey(metaValue(s,g,'ball'))===metaKey(filters.ball)))})).filter(s=>s.games.length);}
export function metadataValues(sessions=[],kind){const vals=new Map();for(const s of sessions){if(kind==='center'||kind==='oil'){const v=metaValue(s,null,kind),k=metaKey(v);if(k)vals.set(k,v);continue}for(const g of(s.games||[])){if(!gameComplete(g))continue;const v=metaValue(s,g,kind),k=metaKey(v);if(k)vals.set(k,v)}}return[...vals.values()].sort((a,b)=>a.localeCompare(b));}
export function summarizeBreakdown(sessions=[],kind){return metadataValues(sessions,kind).map(label=>{const subset=(kind==='center'||kind==='oil')?sessions.filter(s=>metaKey(metaValue(s,null,kind))===metaKey(label)):sessions.map(s=>({...s,games:(s.games||[]).filter(g=>metaKey(metaValue(s,g,kind))===metaKey(label))})).filter(s=>s.games.length),st=summarizeSessions(subset);return{label,...st}}).filter(x=>x.games).sort((a,b)=>b.games-a.games||(b.average??0)-(a.average??0)||a.label.localeCompare(b.label));}
export function summarizeSessions(sessions=[]){const scores=[],leaveStats={};let strikes=0,strikeOpps=0,spares=0,spareOpps=0,highSeries=null,splitOpps=0,splitMade=0,singleOpps=0,singleMade=0,tenOpps=0,tenMade=0;for(const s of sessions){let series=0,games=0;for(const g of(s.games||[])){if(!gameComplete(g))continue;const sc=scoreGame(g).final;scores.push(sc);series+=sc;games++;g.frames.slice(0,10).forEach((f,i)=>{if(!f.rolls.length)return;strikeOpps++;if(f.rolls[0]===10){strikes++;return}if(f.rolls.length>=2){spareOpps++;const made=f.rolls[0]+f.rolls[1]===10;if(made)spares++;const leave=(f.leave||[]).map(Number).sort((a,b)=>a-b);if(leave.length){const key=leave.join('-'),split=!!(f.split||isSplitLeave(leave)),row=leaveStats[key]||(leaveStats[key]={label:key,attempts:0,made:0,split,pins:leave});row.attempts++;if(made)row.made++;row.split=row.split||split;if(leave.length===1){singleOpps++;if(made)singleMade++;if(leave[0]===10){tenOpps++;if(made)tenMade++;}}if(split){splitOpps++;if(made)splitMade++;}}}});}if(games)highSeries=Math.max(highSeries??0,series);}const sum=scores.reduce((a,b)=>a+b,0),leaveDetails=Object.values(leaveStats).map(x=>({...x,pct:x.attempts?x.made/x.attempts*100:null})).sort((a,b)=>b.attempts-a.attempts||b.made-a.made||a.label.localeCompare(b.label)).slice(0,12),topLeaves=leaveDetails.map(x=>[x.label,x.attempts]);return{games:scores.length,average:scores.length?sum/scores.length:null,highGame:scores.length?Math.max(...scores):null,highSeries,strikePct:strikeOpps?strikes/strikeOpps*100:null,sparePct:spareOpps?spares/spareOpps*100:null,splitPct:splitOpps?splitMade/splitOpps*100:null,singlePinPct:singleOpps?singleMade/singleOpps*100:null,tenPinPct:tenOpps?tenMade/tenOpps*100:null,splitOpps,splitMade,singleOpps,singleMade,tenOpps,tenMade,topLeaves,leaveDetails};}
