import assert from'node:assert/strict';
import{emptyFrames,addRoll,scoreGame,gameComplete,handicapPins,filterSessionsByMeta,metadataValues,summarizeBreakdown,runningLeagueAverage,getCurrentFirstBallSetup,setCurrentFirstBallSetup,captureFirstBallSetup,undoRoll}from'../scoring.mjs';
const game=()=>({frames:emptyFrames()}),rolls=(g,a)=>(a.forEach(x=>addRoll(g,x)),g);
let g=rolls(game(),Array(20).fill(0));assert.equal(scoreGame(g).final,0);
g=rolls(game(),Array(21).fill(5));assert.equal(scoreGame(g).final,150);
g=rolls(game(),Array(12).fill(10));assert.equal(scoreGame(g).final,300);
g=game();const a=[];for(let i=0;i<10;i++)a.push(9,0);rolls(g,a);assert.equal(scoreGame(g).final,90);
g=game();const b=[];for(let i=0;i<10;i++)b.push(5,5);b.push(5);rolls(g,b);assert.equal(scoreGame(g).final,150);assert.equal(gameComplete(g),true);
assert.equal(handicapPins(180,90,210),27);assert.equal(handicapPins(180),36);assert.equal(handicapPins(220,90,210),0);assert.equal(handicapPins(null,90,210),null);
console.log('scoring and handicap tests passed');
const ga=rolls(game(),Array(20).fill(0));ga.lane='5-6';ga.ballUsed='Ball A';
const gb=rolls(game(),Array(21).fill(5));gb.lane='7-8';gb.ballUsed='Ball B';
const ss=[{center:'Center A',oilPattern:'House',games:[ga,gb]}];
assert.deepEqual(metadataValues(ss,'ball'),['Ball A','Ball B']);assert.deepEqual(metadataValues(ss,'lane'),['5-6','7-8']);
assert.equal(filterSessionsByMeta(ss,{center:'Center A',oil:'House',ball:'Ball B'})[0].games.length,1);
assert.equal(filterSessionsByMeta(ss,{center:'center a',oil:'house',ball:'ball b'})[0].games.length,1);
const gc=rolls(game(),Array(20).fill(0));gc.ballUsed='BALL A';gc.lane='5-6';const ss2=[{center:'CENTER A',oilPattern:'house',games:[ga,gc]}];assert.deepEqual(metadataValues(ss2,'ball'),['BALL A']);assert.equal(summarizeBreakdown(ss2,'ball').length,1);
const bd=summarizeBreakdown(ss,'ball');assert.equal(bd.length,2);assert.equal(bd.find(x=>x.label==='Ball B').average,150);
const filteredCenter=filterSessionsByMeta([{center:'Center A',oilPattern:'House',games:[ga]},{center:'Center B',oilPattern:'House',games:[gb]}],{center:'Center A'});const centerBalls=summarizeBreakdown(filteredCenter,'ball');assert.deepEqual(centerBalls.map(x=>x.label),['Ball A']);
console.log('metadata analytics tests passed');

const histGame=rolls(game(),Array(21).fill(5));
const histSession={league:'Example League',date:'2026-09-08',gameCount:3,enteringAverage:180,games:[histGame]};
const beforeCorrect=runningLeagueAverage([histSession]).currentAverage;
histSession.enteringAverage=190;
const afterCorrect=runningLeagueAverage([histSession]).currentAverage;
assert.equal(runningLeagueAverage([histSession]).seedAverage,190);
assert.ok(afterCorrect>beforeCorrect);
console.log('historical entering-average recalculation test passed');

const makeOpen=(first,second)=>{const a=[];for(let i=0;i<10;i++)a.push(first,second);return rolls(game(),a)};
const establishGames=[makeOpen(8,1),makeOpen(7,2),makeOpen(6,3)];
const establishSession={league:'Test Establish',date:'2026-09-01',gameCount:3,enteringAverage:180,games:establishGames};
const beforeEstablished=runningLeagueAverage([establishSession],{mode:'establish',games:9});assert.equal(beforeEstablished.currentAverage,180);assert.equal(beforeEstablished.established,false);
const establishSessions=[0,1,2].map((n)=>({league:'Test Establish',date:'2026-09-0'+(n+1),gameCount:3,enteringAverage:180,games:[makeOpen(6+n,3-n),makeOpen(6+n,3-n),makeOpen(6+n,3-n)]}));
const afterEstablished=runningLeagueAverage(establishSessions,{mode:'establish',games:9});assert.equal(afterEstablished.games,9);assert.equal(afterEstablished.established,true);assert.equal(afterEstablished.currentAverage,Math.floor(afterEstablished.pins/9));assert.notEqual(afterEstablished.currentAverage,180);
console.log('league average establishment tests passed');

const setupGame=game();
setCurrentFirstBallSetup(setupGame,{ballUsed:'Venom Cobra',standBoard:28,targetBoard:13});
captureFirstBallSetup(setupGame,0);addRoll(setupGame,10);
setCurrentFirstBallSetup(setupGame,{ballUsed:'Venom Cobra',standBoard:30,targetBoard:13});
captureFirstBallSetup(setupGame,1);addRoll(setupGame,10);
assert.deepEqual(setupGame.frames[0].firstBallSetup,{ballUsed:'Venom Cobra',standBoard:28,targetBoard:13});
assert.deepEqual(setupGame.frames[1].firstBallSetup,{ballUsed:'Venom Cobra',standBoard:30,targetBoard:13});
assert.deepEqual(getCurrentFirstBallSetup(setupGame),{ballUsed:'Venom Cobra',standBoard:30,targetBoard:13});
assert.equal(undoRoll(setupGame),true);assert.equal(setupGame.frames[1].firstBallSetup,undefined);
assert.deepEqual(setupGame.frames[0].firstBallSetup,{ballUsed:'Venom Cobra',standBoard:28,targetBoard:13});
const legacySetupGame=game();legacySetupGame.ballUsed='Legacy Ball';
assert.deepEqual(getCurrentFirstBallSetup(legacySetupGame),{ballUsed:'Legacy Ball',standBoard:null,targetBoard:null});
console.log('first-ball setup and legacy compatibility tests passed');
