import assert from'node:assert/strict';
import{emptyFrames,addRoll,scoreGame,gameComplete,handicapPins,filterSessionsByMeta,metadataValues,summarizeBreakdown,runningLeagueAverage}from'../scoring.mjs';
const game=()=>({frames:emptyFrames()}),rolls=(g,a)=>(a.forEach(x=>addRoll(g,x)),g);
let g=rolls(game(),Array(20).fill(0));assert.equal(scoreGame(g).final,0);
g=rolls(game(),Array(21).fill(5));assert.equal(scoreGame(g).final,150);
g=rolls(game(),Array(12).fill(10));assert.equal(scoreGame(g).final,300);
g=game();const a=[];for(let i=0;i<10;i++)a.push(9,0);rolls(g,a);assert.equal(scoreGame(g).final,90);
g=game();const b=[];for(let i=0;i<10;i++)b.push(5,5);b.push(5);rolls(g,b);assert.equal(scoreGame(g).final,150);assert.equal(gameComplete(g),true);
assert.equal(handicapPins(180,90,210),27);assert.equal(handicapPins(180),36);assert.equal(handicapPins(220,90,210),0);assert.equal(handicapPins(null,90,210),null);
console.log('scoring and handicap tests passed');
const ga=rolls(game(),Array(20).fill(0));ga.lane='5-6';ga.ballUsed='Ball A';
const gb=rolls(game(),Array(21).fill(5));gb.lane='7-8';gb.ballUsed='Ball B';
const ss=[{center:'Center A',oilPattern:'House',games:[ga,gb]}];
assert.deepEqual(metadataValues(ss,'ball'),['Ball A','Ball B']);assert.deepEqual(metadataValues(ss,'lane'),['5-6','7-8']);
assert.equal(filterSessionsByMeta(ss,{center:'Center A',oil:'House',ball:'Ball B'})[0].games.length,1);
assert.equal(filterSessionsByMeta(ss,{center:'center a',oil:'house',ball:'ball b'})[0].games.length,1);
const gc=rolls(game(),Array(20).fill(0));gc.ballUsed='BALL A';gc.lane='5-6';const ss2=[{center:'CENTER A',oilPattern:'house',games:[ga,gc]}];assert.deepEqual(metadataValues(ss2,'ball'),['BALL A']);assert.equal(summarizeBreakdown(ss2,'ball').length,1);
const bd=summarizeBreakdown(ss,'ball');assert.equal(bd.length,2);assert.equal(bd.find(x=>x.label==='Ball B').average,150);
console.log('metadata analytics tests passed');
