import assert from'node:assert/strict';
import{normalizeTelemetryEvent,normalizeTelemetryBatch,telemetryPlatform}from'../telemetry.mjs';
const good={id:'evt-12345678',deviceId:'dev-12345678',event:'series_completed',appVersion:'public-v22',occurredAt:'2026-09-20T20:00:00Z',installMode:'installed',platform:'android',score:300,league:'Secret League'};
assert.deepEqual(normalizeTelemetryEvent(good),{id:'evt-12345678',deviceId:'dev-12345678',event:'series_completed',appVersion:'public-v22',occurredAt:'2026-09-20T20:00:00.000Z',installMode:'installed',platform:'android'});
assert.equal(normalizeTelemetryEvent({...good,event:'score_saved'}),null);
assert.equal(normalizeTelemetryEvent({...good,id:'bad'}),null);
const batch=normalizeTelemetryBatch({events:Array(30).fill(good)});assert.equal(batch.length,25);
assert.equal('score'in batch[0],false);assert.equal('league'in batch[0],false);
assert.equal(telemetryPlatform('Mozilla Android'),'android');assert.equal(telemetryPlatform('iPhone'),'ios');
console.log('telemetry privacy allowlist tests passed');
